### PR TITLE
Keep folding state when modifying whitespace

### LINKED ISSUE #20: Modifying file unfolds code
When whitespace is trimmed, or a final newline is inserted or removed, the document's fold state is not always maintained.

### Steps to Reproduce the Issue
1. Create an `.editorconfig` file as follows:
```
root=true
[*]
trim_trailing_whitespace=true
insert_final_newline=true

```
2. Create a C++ file in the same directory as follows:
```cpp
int dosomething(void) {
	// add whitespace to the right >>>          
}

int main(void) {
	return 0;
}
```
3. Fold the code at the 2 fold points. It will now look like this:
capture2

4. Save the file
5. The 2 fold points open up

### Expected Behavior
The folding to stay the same once saved. It can be very distracting to have code move around when you save the file.

### Debug Information

Tested using latest HEAD (85d675783011893a53c78f98b0a25155ef64ab7d)

```
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : BetterMultiSelection.dll DoxyIt.dll DSpellCheck.dll ElasticTabstops.dll LuaScript.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExport.dll PluginManager.dll PythonScript.dll Scintillua++.dll SurroundSelection.dll 
```

### PR DESCRIPTION
**Pull request by dail8859**
Closes #20. Disabling the automatic fold behavior makes it so Scintilla does not show the text when it is being modified.

### CODE REVIEW

File: src/PluginDefinition.cpp [hunk 1]
```diff
@@ -296,6 +296,12 @@ void onBeforeSave(HWND hWnd)
         }
     }
 
+    // Save the folding behavior and set it to 0 to keep folds from opening
+    // when modifying the file.
+    HWND curScintilla = getCurrentScintilla();
+    int automatic_fold = SendMessage(curScintilla, SCI_GETAUTOMATICFOLD, 0, 0);
+    SendMessage(curScintilla, SCI_SETAUTOMATICFOLD, 0, 0);
```
Comment (xuhdev) [inline src/PluginDefinition.cpp]: Is this line necessary? It seems that you will send the automatic fold flag any way.

**Comment by xuhdev** [comment]
@ffes Can you help with testing the PR? It's not easy for me to access Windows nowadays... Thank you!

File: src/PluginDefinition.cpp (hunk 1 above)
Comment (dail8859) [reply src/PluginDefinition.cpp]: Yes. The automatic fold must be set to 0 (disabled) before modifying the file.

Comment (xuhdev) [reply src/PluginDefinition.cpp]: Thanks!

**Comment by xuhdev** [comment]
@dail8859 Cool! Looks like you are clear about everything you did :) I'll just wait for @ffes giving me a confirmation on the testing result, then I'll merge.

**Comment by ffes** [comment]
First impression: it looks good. I will test it ASAP

**Comment by ffes** [comment]
I have testing this a bit and it works as described.

@xuhdev I would merge this PR, or shall I do it?

**Comment by xuhdev** [comment]
Sure :)
